[11.0] Limit the computation of residual to the receivable/payable move lines whose partner match with the invoice's commercial partner.
OCA/OCB pull request #751
Opened 2018-05-28 09:57 UTC by jbeficent

-Limit the computation of residual to the receivable/payable move lines whose partner match with the invoice's commercial partner.
- when assigning payments to invoices, reconcile receivables and payables
  that match with the invoice's commercial partner.

Upstream PR: https://github.com/odoo/odoo/pull/24915
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2018-05-28 22:35 UTC, pedrobaeza requested changes

2018-05-28 22:35 UTC, pedrobaeza commented on addons/account/models/account_invoice.py
> +            if line.account_id == self.account_id and \
Better to avoid `\` and use parenthesis for avoiding interpreter problems

2018-05-28 22:35 UTC, pedrobaeza commented on addons/account/models/account_invoice.py
> +                lambda r: not r.reconciled and
The same with this: enclose the lambda expression into parenthesis

2018-05-29 04:16 UTC, jbeficent commented
@pedrobaeza Thanks. I applied your review comments.

2018-05-29 07:12 UTC, pedrobaeza commented on addons/account/models/account_invoice.py
> +                        not r.reconciled and
Indentation level incorrect

2018-08-05 14:43 UTC, gurneyalex approved these changes

2018-10-28 14:28 UTC, gurneyalex commented on addons/account/models/account_invoice.py
> +                        not r.reconciled and
```suggestion
                    not r.reconciled and
```

2019-04-04 10:33 UTC, mreficent commented
This PR should be closed because the hooks in https://github.com/odoo/odoo/pull/26472 were merged.

2019-04-04 10:38 UTC, pedrobaeza commented
OK, closing

2019-04-04 10:38 UTC, closed without merging