[FIX] 9.0 stock: _complete_name failing
OCA/OCB pull request #761
Opened 2018-07-02 15:49 UTC by mpanarin

Description of the issue/feature this PR addresses:
when package name is False this will throw an error
on the concatenation of bool and unicode

Current behaviour before PR:
Error on trying to read the record with parent set and name = False

Desired behaviour after PR is merged:
No exception thrown )

2018-07-02 15:57 UTC, pedrobaeza commented
Please propose this to Odoo upstream

2018-07-02 15:57 UTC, pedrobaeza approved these changes

2018-07-02 16:42 UTC, mpanarin commented
@pedrobaeza done https://github.com/odoo/odoo/pull/25570

2018-07-03 08:43 UTC, yvaucher approved these changes

2018-08-05 12:39 UTC, gurneyalex approved these changes

2018-08-05 12:40 UTC, gurneyalex requested changes

2018-08-05 12:40 UTC, gurneyalex commented on addons/stock/stock.py
> +                res[m.id] = "%s / %s" %(parent_name, res[m.id])
```res[m.id] = u"%s / %s" % (parent_name, res[m.id])```

(unicode or you may get funky decoding errors if parent_name or res[m.id] contains non ascii chars)

2018-08-06 15:05 UTC, mpanarin commented
@gurneyalex updated

2018-08-16 07:52 UTC, gurneyalex approved these changes

2018-09-03 07:11 UTC, merged